name             'm4'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures m4'
long_description 'Installs/Configures m4'
version          '0.1.0'
